name: helloworld

on:
  workflow_dispatch:
  

  
jobs:
    say_hello:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "HEloo world"
    job2:
        runs-on: ubuntu-24.04
        steps:
          - run: echo "job2 running"
    job3:
        runs-on: ubuntu-24.04
        needs: 
            - job2
            - say_hello
          
